all:
  hosts:
    # s1-domain-test01.nokogerra.lab:
    #   ansible_host: 10.215.102.81
    #   host_ipaddr: 10.215.102.81
    # s1-domain-test02.nokogerra.lab:
    #   ansible_host: 10.215.102.82
    #   host_ipaddr: 10.215.102.82
    s1-kafka-node0[1:3].nokogerra.lab: