# code: language=ansible
---
- name: asd
  hosts: all
  vars:
    domain_name: "nokogerra.lab"
  
  tasks:
#    - name: "Set hostname (FQDN is picked up from the inventory)"
#      ansible.builtin.hostname:
#        name: "{{ inventory_hostname }}"
#    - name: "edit hosts"
#      lineinfile:
#        path: /etc/hosts
#        regexp: "^{{ ansible_host }}"
#        line: "{{ ansible_host }} {{ inventory_hostname }} {{ inventory_hostname_short }}"
    - name: "check"
      debug:
        msg: "{{ host_ipaddr }}"