# code: language=ansible
---
- name: "Configure LVMs, FSes and mount them"
  hosts: all
  vars:
    configure_lvm_and_fs_storages:
      - disk: sdb
        vg_name: nfs_vg
        lvm_name: nfs_lv
        fs_type: ext4
        mount_path: /nfs
#      - disk: sdc
#        vg_name: data2_vg
#        lvm_name: data2_lv
#        fs_type: ext4
#        mount_path: /data2
    move_system_dir_config:
      - source: /var
        dest: /data1
        excludes:
          - /lib
      - source: /var/lib
        dest: /data2
    nfs_server_exports:
      - path: /nfs/export01
        dir_permissions: "0777"
        clients: "*"
        read_write: rw
        sync: sync
        subtree: no_subtree_check
        root_squash: no_root_squash
  roles:
    - mount_nfs
#    - nfs_server
#    - configure_lvm_and_fs
#    - move_system_dir
