# code: language=ansible
---
- name: "Install nfs-common"
  ansible.builtin.apt:
    name: "nfs-common"
    state: present
    update_cache: true

- name: "Mount NFS export"
  ansible.posix.mount:
    path: "{{ local_path }}"
    src: "{{ nfs_source }}"
    fstype: nfs
    state: mounted

- name: "Gather facts"
  ansible.builtin.setup:

- name: "Show NFS mounts"
  ansible.builtin.debug:
    msg: "{{ ansible_facts['mounts'] | selectattr('fstype', 'match', 'nfs.*') | list }}"
