# code: language=ansible
---
- name: "Add nginx repository key"
  ansible.builtin.apt_key:
    url: "{{ install_nginx_repo_key_url }}"
    keyring: "{{ install_nginx_repo_key_file_path }}"

- name: "Add nginx repository"
  ansible.builtin.apt_repository:
    repo: "{{ install_nginx_repo_string }}"
    filename: "{{ install_nginx_repo_file }}"
    state: present

- name: "Install nginx if version is specified"
  ansible.builtin.apt:
    name: "nginx={{ install_nginx_version }}"
    state: present
    allow_downgrade: true
    update_cache: true
  when: install_nginx_version is defined

- name: "Update apt cache"
  ansible.builtin.apt:
    update_cache: true
  when: install_nginx_version is not defined

- name: "Get available nginx versions in nginx repository"
  ansible.builtin.shell: "sudo apt-cache madison nginx | grep 'http://nginx'"
  register: nginx_versions
  when: install_nginx_version is not defined

- name: "Show available nginx versions"
  ansible.builtin.debug:
    msg: "{{ nginx_versions.stdout_lines }}"
  when: install_nginx_version is not defined

- name: "Ask for nginx version to install"
  ansible.builtin.pause:
    prompt: "Enter the nginx version you want to install"
    echo: true
  register: nginx_ver
  when: install_nginx_version is not defined

- name: "Install nginx if version is not specified"
  ansible.builtin.apt:
    name: "nginx={{ nginx_ver.user_input }}"
    state: present
    allow_downgrade: true
    update_cache: true
  when: install_nginx_version is not defined

- name: "Enable and start nginx"
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
