# code: language=ansible
---
- name: "Add nginx repository key"
  ansible.builtin.apt_key:
    url: "{{ install_nginx_repo_key_url }}"
    keyring: "{{ install_nginx_repo_key_file_path }}"

- name: "Add nginx repository"
  ansible.builtin.apt_repository:
    repo: "{{ install_nginx_repo_string }}"
    filename: "{{ install_nginx_repo_file }}"
    state: present

- name: "Install nginx if version is specified"
  ansible.builtin.apt:
    name: "nginx={{ install_nginx_version }}"
    state: present
    allow_downgrade: true
    update_cache: true
  when: install_nginx_version is defined

- name: "Install nginx latest if version is not specified"
  ansible.builtin.apt:
    name: "nginx"
    state: present
    allow_downgrade: true
    update_cache: true
  when: install_nginx_version is not defined
