# code: language=ansible
# IMPORTANT: Do not use dashes "-" in VG and LV names!
# Otherwise an LV path would be like "mydata1--vg-mydata1--lv", so linux will change single dash to the double one.
# Underscore is a good choice to separate words in a LV name.
---
configure_lvm_and_fs_storages:
  - disk: sdb
    vg_name: mydata1_vg
    lvm_name: mydata1_lv
    fs_type: ext4
    mount_path: /mydata1
  - disk: sdc
    vg_name: mydata2_vg
    lvm_name: mydata2_lv
    fs_type: ext4
    mount_path: /mydata2
